

import admin

import urllib,urllib2
url = 'http://www.hacker.org/coil/index.php'
#~ data = urllib.urlencode(values)


data='y=14&x=36&password=a519e085&name=ernie&path=RULDLDRDRURDRDRDLULDRDLDRDLULULDRDLDRDLDRURDRDLULDLDLULDLULURURDRULURURDLDRDLDRURULULDLURURULURURURDRULDLULDRDLDLDLURULDLULDLULDRDLDRURDRDRDLULDLULDLDRDRURDRDLDLURULULULDLDRDLDLDLULDLULURULURDLDRDRURULURURULURDRURULULDLULURULULDRDLDRURDLDLULURULURULURDRURULDLULURURULULURDLDRURURDLULDLDRDLDRDRDRURURDLDLDLDRDRDRURURULURURURDRURDLDLULULDLDLDRDRURDLULDLDRDLDRDLULDLDLDLDRDRURURURDLDRURDRURULURDRURURDRULURDRDLDRURDRURULULDLURULULURDRURULDLULURULURURDRURURDLDRURDRURDLDRDRDLULDLDRDRURDLU'
req = urllib2.Request(url, data)
print req.get_full_url().replace(admin.getpw(),'****')
response = urllib2.urlopen(req)
print 'SUBBED!'